fix crash when launching a world with this seed : 2465602432010453352
the issue was discovered in my modpack

crash report :

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=size, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block betternether:orange_mushroom, it is not an allowed value
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:14614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
    at gg.essential.loader.stage2.EssentialLoader.doInitialize(EssentialLoader.java:367)
    at gg.essential.loader.stage2.EssentialLoaderBase.initialize(EssentialLoaderBase.java:761)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at gg.essential.loader.stage1.EssentialLoaderBase.initialize(EssentialLoaderBase.java:126)
    at gg.essential.loader.stage1.EssentialSetupTweaker.injectIntoClassLoader(EssentialSetupTweaker.java:59)
    at gg.essential.loader.stage0.EssentialSetupTweaker.injectIntoClassLoader(EssentialSetupTweaker.java:135)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=size, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block betternether:orange_mushroom, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:227)
    at paulevs.betternether.blocks.BlockOrangeMushroom.getStateFromMeta(BlockOrangeMushroom.java:74)
    at net.minecraft.block.Block.getStateById(Block.java:2736)
    at net.minecraft.client.network.NetHandlerPlayClient.handleSpawnObject(NetHandlerPlayClient.java:437)
    at net.minecraft.network.play.server.SPacketSpawnObject.processPacket(SourceFile:124)
    at net.minecraft.network.play.server.SPacketSpawnObject.processPacket(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.redirect$zlk000$patcher$ignorePacketsFromClosedConnections(SourceFile:523)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 34 more